---
platforms:
  - name: instance
    image: ubuntu:20.04
    pre_build_image: true
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
