---
- name: Check if Tilix profile file exists
  stat:
    path: "{{ tilix_profile_filename }}"
  register: tilix_profile_file

- name: Load Tilix profile if file exists
  shell: "dconf load /com/gexperts/Tilix/ < {{ tilix_profile_filename }}"
  when: tilix_profile_file.stat.exists
  notify: Restart Tilix
