---
show_home: false
show_trash: false
titlebar_uses_system_font: true

desktop_background:
  - picture-options 'none'
  - picture-uri ''
  - picture-uri-dark ''
  - primary-color '#00008B'
  - show-desktop-icons false

desktop_interface:
  - clock-format '24h'
  - clock-show-date true
  - clock-show-seconds false
  - clock-show-weekday true
  - color-scheme 'prefer-dark'
  - document-font-name 'Inconsolata Nerd Font 12'
  - font-name 'Inconsolata Nerd Font 12'
  - monospace-font-name 'Inconsolata Nerd Font Mono 12'

dock:
  - autohide true
  - dash-max-icon-size 40
  - dock-position 'LEFT'
  - extend-height false
  - show-mounts false

disabled_services:
  - apt-daily.service
  - apt-daily-upgrade.service
