---
gnome_settings_dock_autohide: true
gnome_settings_dock_extend_height: false
gnome_settings_dock_icon_size: 40
gnome_settings_dock_position: 'LEFT'
gnome_settings_dock_show_mounts: false
gnome_settings_show_home: false
gnome_settings_show_trash: false
gnome_settings_titlebar_uses_system_font: true

gnome_settings_desktop_background:
  - picture-uri ''
  - picture-uri-dark ''
  - picture-options 'none'
  - primary-color '#00008B'
  - show-desktop-icons false

gnome_settings_desktop_interface:
  - clock-format '24h'
  - clock-show-date true
  - clock-show-seconds false
  - clock-show-weekday true
  - color-scheme 'prefer-dark'
  - monospace-font-name 'Inconsolata Nerd Font Mono 12'
  - font-name 'Inconsolata Nerd Font 12'
  - document-font-name 'Inconsolata Nerd Font 12'

gnome_settings_disabled_services:
  - apt-daily.service
  - apt-daily-upgrade.service
