---
gnome_settings_show_home: false
gnome_settings_show_trash: false
gnome_settings_titlebar_uses_system_font: true
gnome_settings_screensaver_idle_activation_enabled: false
gnome_settings_lock_screen_enabled: false
gnome_settings_lock_screen_disable_lock_screen: true

gnome_settings_desktop_background:
  - picture-options 'none'
  - picture-uri ''
  - picture-uri-dark ''
  - primary-color '#00007D'
  - show-desktop-icons false

gnome_settings_desktop_interface:
  - clock-format '24h'
  - clock-show-date true
  - clock-show-seconds false
  - clock-show-weekday true
  - color-scheme 'prefer-dark'
  - document-font-name 'Inconsolata Nerd Font 12'
  - font-name 'Inconsolata Nerd Font 12'
  - monospace-font-name 'Inconsolata Nerd Font Mono 12'

gnome_settings_dock:
  - autohide true
  - dash-max-icon-size 40
  - dock-position 'LEFT'
  - extend-height false
  - show-mounts false

gnome_settings_disabled_services:
  - apt-daily.service
  - apt-daily-upgrade.service

gnome_settings_dock_settings:
  animate_appicon_hover: true
  animate_appicon_hover_animation_extent: "{'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}"
  animate_appicon_hover_animation_type: 'RIPPLE'
  appicon_margin: 2
  appicon_padding: 2
  available_monitors: [0]
  dot_position: 'BOTTOM'
  hotkeys_overlay_combo: 'TEMPORARILY'
  intellihide: true
  leftbox_padding: -1
  panel_anchors: '{"0":"MIDDLE"}'
  panel_lengths: '{"0":100}'
  panel_sizes: '{"0":34}'
  primary_monitor: 0
  show_appmenu: false
  show_favorites_all_monitors: false
  status_icon_padding: -1
  trans_bg_color: '#00007d'
  trans_use_custom_bg: true
  trans_use_custom_opacity: true
  trans_use_dynamic_opacity: true
  tray_padding: -1
  window_preview_title_position: 'TOP'
