---
dependencies:
  - role: add_repo
    vars:
      filename: 'hashicorp'
      key_url: 'https://apt.releases.hashicorp.com/gpg'
      repo_name: 'HashiCorp'
      repo_urls:
        - 'deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
