package_groups:
  common:
    - ansible
    - ansible-lint
    - aptitude
    - build-essential
    - ca-certificates
    - curl
    - dconf-editor
    - dkms
    - docker-ce
    - docker-compose
    - docker-scan-plugin
    - dos2unix
    - elinks
    - expect
    - git
    - htop
    - jq
    - "linux-headers-{{ ansible_kernel }}"
    - markdown
    - mlocate
    #- pandoc
    - parallel
    - python3-pip
    - tmux
    - tree
    - unzip
    - vim
    - wget
    - zip
  gui:
    - fonts-inconsolata
    - gnome-tweaks
    - tilix
  gnome_settings:
    - gnome-shell-extensions
    - gnome-shell-extension-desktop-icons-ng
    - gnome-tweaks
    - tilix
  hledger:
    - hledger
    - hledger-ui
  vscode:
    - code # This is the package name for Visual Studio Code
