package_groups:
  common:
    - ansible
    - ansible-lint
    - aptitude
    - build-essential
    - ca-certificates
    - curl
    - dconf-editor
    - dkms
    - dos2unix
    - elinks
    - expect
    - git
    - htop
    - jq
    - "linux-headers-{{ ansible_kernel }}"
    - markdown
    - mlocate
    #- pandoc
    - parallel
    - python3-pip
    - tmux
    - tree
    - unzip
    - vim
    - wget
    - zip
  gui:
    - fonts-inconsolata
    - gnome-tweaks
    - tilix
  hledger:
    - hledger
    - hledger-ui
  vscode:
    - code # This is the package name for Visual Studio Code
  docker:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  gcloud:
    - google-cloud-cli
