# Define package groups
package_groups:
  common:
    - ansible
    - ansible-lint
    - aptitude
    - build-essential
    - ca-certificates
    - curl
    - dconf-editor
    - dkms
    - docker-ce
    - docker-compose
    - docker-scan-plugin
    - dos2unix
    - elinks
    - expect
    - git
    - htop
    - jq
    - "linux-headers-{{ ansible_kernel }}"
    - markdown
    - mlocate
    #- pandoc
    - parallel
    - tmux
    - tree
    - unzip
    - vim
    - wget
    - zip
  gui:
    - fonts-inconsolata
    - gnome-tweaks
    - tilix
