gnome_settings_packages:
  - dbus-x11
  - fontconfig
  - gnome-shell-extension-desktop-icons-ng
  - gnome-shell-extension-manager
  - gnome-shell-extensions
  - gnome-startup-applications
  - gnome-tweaks
  - tilix
  - wmctrl
