---
dependencies:
  - role: add_repo
    vars:
      filename: google-cloud
      key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      repo_name: Google Cloud
      repo_urls:
       - deb https://packages.cloud.google.com/apt cloud-sdk main

  - role: ansible.builtin.package
    vars:
      name: "{{ gcloud_packages }}"
      state: "present"
    vars:
      packages:
        - google-cloud-cli
