---
dependencies:
  - role: add_repo
    vars:
      filename: nodesource
      key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      repo_name: NodeSource
      repo_urls:
        - deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main
        # - "deb-src https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
