# Define a hash of available repositories
repos:
  google-cloud:
    filename: google-cloud
    key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    repo_name: Google Cloud
    repo_url: deb https://packages.cloud.google.com/apt cloud-sdk main
  hashicorp:
    filename: hashicorp
    key_url: https://apt.releases.hashicorp.com/gpg
    repo_name: Hashicorp
    repo_url: deb https://apt.releases.hashicorp.com focal main
  microsoft:
    filename: microsoft
    key_url: https://packages.microsoft.com/keys/microsoft.asc
    repo_name: Microsoft
    repo_url: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_release }}/prod {{ ansible_distribution_release }} main"
